Repository rye/eb, pull requests merged in 2020-10, with the labels that each got.

#86 cargo: Update libc to version 0.2.79
  Cargo.lock
Labels: dependencies

#82 Max flag added
  src/lib.rs
  src/main.rs
Labels: Area: CLI 🤖, Area: Logic 🔎, Type: New Feature 📰

#87 Reformat
  src/main.rs
Labels: Type: Refactoring ♻
